name: Deploy Bicep for Infrastructure
  on: 
    workflow_dispatch:
    push:
    branches: 
    - main


jobs: 
  build: 
    # Build front end environment
    name: build front end
    runs-on: ubuntu-latest
    steps: 
      # Checkout code
      - uses: actions/checkout@main

      # Log into Azure
        # This describes how to generate and store azure credentials: https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows#use-the-azure-login-action-with-a-service-principal-secret
      - uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            enable-AzPSSession: true

      # Deploy Front end Bicep File
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: BicepHackathonTest
          deploymentMode: incremental
          template: ./infra/main.bicep
          failOnStdErr: true

      

